<?php
//~ Template for index.php
// variables:
//  $template - page to be displayed (included)
//  $flashes - flash messages
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $head_template->getTitle(); ?></title>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
        <meta name="description" content="<?= $head_template->getDescription(); ?>" />
        <link rel="stylesheet" type="text/css" href="../web/css/main.css">
        <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Montserrat" rel="stylesheet">
    </head>   

    <body>
        <div class="site-wrapper">
            <?php require $template; ?>
        </div>
    </body>
</html>
